### ISSUE TITLE
proposed schema items

### ISSUE THREAD

**Issue by satra** [dandi/dandi-core#3]
Any objections to [current proposed schema].(https://docs.google.com/presentation/d/16HFZVFYgmq6N4uH4HIQGGySrEwQfOZOj-staBEdU_7Q/edit#slide=id.g76c132f7b7_0_6)

**Comment by mgrauer** [comment]
Hard for me to say, looking at it in those slides it isn't clear to me what are the diffs compared to our current schema. Have we tried implementing this new proposed schema with some of our existing dandisets as a test run?

**Comment by satra** [comment]
@mgrauer - we should be able to map most things over. haven't actually done it. but this is more at the level of the conceptual schema not an implementation. i will generate schema.org like elements for each of them.

**Comment by yarikoptic** [comment]
I think this is at large solved in dandi-schema thus will close
