### ISSUE TITLE
FOI: biolink-model

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-core#5]
I didn't want to pollute #4 but wanted to share the knowledge from @nicholsn about 
https://biolink.github.io/biolink-model/
where they also established a model specification/mapping, from the source of  https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml  (repo is a bit messy since produced artifacts are all the way around).

Might be of interest also for bids (I might cross link later)

**Comment by satra** [comment]
yup it's referred to in our dataset descriptor presentation. 

also regarding structure, it will likely look similar to the proposed release for reproschema: https://github.com/satra/reproschema/tree/rel-1.0-rc1/releases/1.0-rc1
